# pull official base image
FROM node:lts-alpine

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install app dependencies
COPY package.json ./
COPY package-lock.json ./
RUN npm install --location=global react-scripts@latest
RUN npm install -g serve

# add app
COPY . ./

# build production app
RUN npm install
RUN npm run build

# start app
CMD ["serve", "-s", "build"]
