version: "2.2"
services:
  goodhouse-client:
    image: lastradev/goodhouse-client:latest
    network_mode: host
    restart: unless-stopped
    container_name: goodhouse-client
    depends_on:
      - goodhouse-server
  goodhouse-server:
    image: lastradev/goodhouse-server:latest
    network_mode: host
    restart: unless-stopped
    container_name: goodhouse-server
